### PR TITLE
Add support for all versions of 0.15

### PR DESCRIPTION
**Pull request by TheAppleGamer**

### CODE REVIEW

**Comment by daniktheboss** [comment]
Won't work. If a protocol number is changed, the protocols itself had to change.

**Comment by TheAppleGamer** [comment]
False, next time try testing it before saying it won't work, every other server software I use/own updates info.php protocol and works fine!

**Comment by daniktheboss** [comment]
False, you updated only the protocol but the mcpe version number is "0.15.x beta"

**Comment by XtremePlayzCODE** [comment]
Tip: See MCPE compatibility. `0.15.x`. Which means any version of `0.15`.

**Comment by daniktheboss** [comment]
"Facepalm" protocol version would not let them join

**Comment by XtremePlayzCODE** [comment]
Exactly.

**Comment by TheAppleGamer** [comment]
Protocol updates in some versions of MCPE, imbecile!

**Comment by TheAppleGamer** [comment]
https://github.com/iTXTech/Genisys/commit/5fc285462c5eb8c2c1a65a1f503b857116928af6
https://github.com/KryptonicDevs/Kryptonic/commit/e592d147882ab829e353dec259ec5620a7c91495
https://github.com/ClearSkyTeam/ClearSky/commit/e770bb190962dea2857bf5e29b3797075ccc8016

**Comment by daniktheboss** [comment]
He updated the protocol AND version.. you updated just the protocol

**Comment by TheAppleGamer** [comment]
Check ClearSky, I got 0.15.9 for them, but you guys are obviously too stupid to actually understand code.

**Comment by daniktheboss** [comment]
Too stupid? This project is dead and you still commit to it? Think again who's stupid LOL

**Comment by TheAppleGamer** [comment]
There is always possibility to revive a project, so does it truly make me stupid? I probably know more than you, you are merely a noob.

**Comment by daniktheboss** [comment]
Revive a project that has been forked off clearsky... why? And you know more then me? Please, I am developing a mcpe server with python while you just change digits to join!

**Comment by caspervanneck** [comment]
There is a Change from 0.15.9 not 0.15.90

**Comment by XtremePlayzCODE** [comment]
Does not allow older protocols to connect.

**Comment by XtremePlayzCODE** [comment]
Casper, please don't merge again, I will debug this pull until I find out this does work with old and new versions

**Pull request merged**
